name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 17
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - uses: coursier/cache-action@v6
    - run: sbt scalafmtSbtCheck scalafmtCheckAll test scripted
    - run: rm -rf $HOME/.ivy2/local
